require('base')
require('colorscheme')
require('maps')
require('plugins')

require('configs.alpha')
require('configs.nvim-tree')
require('configs.bufferline')
require('configs.lualine')
require('configs.toggleterm')
require('configs.telescope')
require('configs.indent-blankline')

require('configs.treesitter')
require('configs.mason')
require('lsp.cmp')
require('lsp.lspconfig')
require('lsp.null-ls')
require('lsp.lspsaga')

require('configs.autopairs')
require('configs.ts-autotag')
require('configs.surround')
require('configs.hop')
require('configs.comment')

require('configs.auto-save')
require('configs.gitsigns')
-- require('configs.scroll')

require('configs.copilot')
